// src-old/components/openflow/AgentEdge.svelte
<script lang="ts">
    interface Props {
        sourceX: number;
        sourceY: number;
        targetX: number;
        targetY: number;
        isActive?: boolean;
        label?: string;
    }

    let { 
        sourceX, 
        sourceY, 
        targetX, 
        targetY, 
        isActive = false,
        label = ''
    }: Props = $props();

    const nodeWidth = 160;
    const nodeHeight = 70;

    const path = $derived.by(() => {
        // Connect bottom-center of source to top-center of target (vertical layout)
        const startX = sourceX + nodeWidth / 2;
        const startY = sourceY + nodeHeight;
        const endX = targetX + nodeWidth / 2;
        const endY = targetY;

        const dy = endY - startY;

        if (dy >= 0) {
            // Normal downward flow: smooth vertical bezier
            const controlOffset = Math.max(dy * 0.4, 20);
            return `M ${startX} ${startY} C ${startX} ${startY + controlOffset}, ${endX} ${endY - controlOffset}, ${endX} ${endY}`;
        } else {
            // Feedback loop going upward: route around the right side so it doesn't overlap nodes
            const sideOffset = 90;
            const verticalPad = 30;
            return `M ${startX} ${startY} C ${startX + sideOffset} ${startY + verticalPad}, ${endX + sideOffset} ${endY - verticalPad}, ${endX} ${endY}`;
        }
    });

    const midpoint = $derived.by(() => {
        return {
            x: (sourceX + nodeWidth / 2 + targetX + nodeWidth / 2) / 2,
            y: (sourceY + nodeHeight + targetY) / 2
        };
    });

    // Use derived IDs so marker references always match the rendered <marker> elements
    const markerId = $derived(`arrow-${sourceX}-${sourceY}-${targetX}-${targetY}`);
    const markerActiveId = $derived(`arrow-active-${sourceX}-${sourceY}-${targetX}-${targetY}`);
</script>

<g class="agent-edge" class:active={isActive}>
    <defs>
        <marker
            id={markerId}
            viewBox="0 0 10 10"
            refX="9"
            refY="5"
            markerWidth="6"
            markerHeight="6"
            orient="auto-start-reverse"
        >
            <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--ui-border)" />
        </marker>
        <marker
            id={markerActiveId}
            viewBox="0 0 10 10"
            refX="9"
            refY="5"
            markerWidth="6"
            markerHeight="6"
            orient="auto-start-reverse"
        >
            <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--ui-accent)" />
        </marker>
    </defs>

    <path
        class="edge-path-bg"
        class:dashed={!isActive}
        d={path}
        marker-end={isActive ? undefined : `url(#${markerId})`}
    />

    {#if isActive}
        <path
            class="edge-path-active"
            d={path}
            marker-end={`url(#${markerActiveId})`}
        />
    {/if}

    {#if label}
        <text
            class="edge-label"
            x={midpoint.x}
            y={midpoint.y - 6}
        >
            {label}
        </text>
    {/if}
</g>

<style>
    .agent-edge {
        pointer-events: none;
    }

    .edge-path-bg {
        fill: none;
        stroke: var(--ui-border-soft, #3a3a3a);
        stroke-width: 1.5;
        transition: stroke 0.3s ease, opacity 0.3s ease;
    }

    .edge-path-bg.dashed {
        stroke-dasharray: 4 6;
        opacity: 0.5;
    }

    .edge-path-active {
        fill: none;
        stroke: var(--ui-accent, #6b8aff);
        stroke-width: 2.5;
        stroke-dasharray: 8 4;
        animation: flow 0.8s linear infinite;
        opacity: 0.9;
    }

    @keyframes flow {
        from {
            stroke-dashoffset: 24;
        }
        to {
            stroke-dashoffset: 0;
        }
    }

    .edge-label {
        fill: var(--ui-text-muted, #888);
        font-size: 11px;
        text-anchor: middle;
        dominant-baseline: middle;
    }
</style>

// src/components/openflow/agent-edge.tsx
import type { PositionedNode } from "@/lib/openflow-graph";
import { NODE_W, NODE_H } from "@/lib/openflow-graph";
import type { EdgeData } from "@/lib/openflow-graph";

interface AgentEdgeProps {
  edge: EdgeData;
  nodes: Map<string, PositionedNode>;
}

export function AgentEdge({ edge, nodes }: AgentEdgeProps) {
  const source = nodes.get(edge.from);
  const target = nodes.get(edge.to);
  if (!source || !target) return null;

  const sx = source.x + NODE_W / 2;
  const sy = source.y + NODE_H;
  const tx = target.x + NODE_W / 2;
  const ty = target.y;

  const isDownward = ty > sy;
  const isActive = edge.label === "assign" || edge.label === "build" || edge.label === "test";

  let d: string;
  if (isDownward) {
    // Standard downward flow: vertical cubic bezier
    const cy1 = sy + (ty - sy) * 0.4;
    const cy2 = sy + (ty - sy) * 0.6;
    d = `M ${sx} ${sy} C ${sx} ${cy1}, ${tx} ${cy2}, ${tx} ${ty}`;
  } else {
    // Feedback loop: route around the right side
    const offsetX = Math.max(NODE_W, Math.abs(tx - sx)) + 40;
    const midX = Math.max(sx, tx) + offsetX;
    d = `M ${sx} ${sy} C ${midX} ${sy}, ${midX} ${ty}, ${tx} ${ty}`;
  }

  // Label position at midpoint
  const mx = (sx + tx) / 2;
  const my = (sy + ty) / 2;

  return (
    <g>
      <path
        d={d}
        fill="none"
        stroke={isActive ? "var(--color-primary)" : "var(--color-border)"}
        strokeWidth={isActive ? 1.5 : 1}
        strokeDasharray={isActive ? undefined : "4 3"}
        opacity={isActive ? 0.8 : 0.4}
        markerEnd="url(#arrowhead)"
      />
      {isActive && (
        <path
          d={d}
          fill="none"
          stroke="var(--color-primary)"
          strokeWidth={1.5}
          strokeDasharray="8 4"
          opacity={0.6}
          style={{
            animation: "dash-flow 1s linear infinite",
          }}
        />
      )}
      <style>{`@keyframes dash-flow { to { stroke-dashoffset: -12; } }`}</style>
      {edge.label && (
        <text
          x={mx}
          y={my - 6}
          textAnchor="middle"
          fill="var(--color-muted-foreground)"
          fontSize={9}
          className="select-none"
        >
          {edge.label}
        </text>
      )}
    </g>
  );
}
