// src/components/terminal/TerminalPane.tsx
import { useEffect, useRef, useCallback } from "react";
import { Terminal } from "@xterm/xterm";
import type { ITheme } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { isAppShortcut } from "@/lib/app-shortcuts";
import {
  writeToPty,
  resizePty,
  detachPtyOutput,
  attachPtyOutput,
  getTerminalStatus,
  Channel,
} from "@/tauri/commands";
import { onTerminalStatus } from "@/tauri/events";
// TODO: re-enable as "system theme" option in settings
// import { useThemeColors } from "@/hooks/use-theme-colors";
import { useTauriEvent } from "@/hooks/use-tauri-event";
import type { TerminalStatusPayload } from "@/tauri/types";

interface Props {
  sessionId: string;
  focused: boolean;
  visible: boolean;
  title: string;
}

// Static ANSI palette — doesn't change with presets
const ANSI_COLORS = {
  black: "#09090b",
  red: "#ef4444",
  green: "#22c55e",
  yellow: "#eab308",
  blue: "#3b82f6",
  magenta: "#a855f7",
  cyan: "#06b6d4",
  white: "#fafafa",
  brightBlack: "#52525b",
  brightRed: "#f87171",
  brightGreen: "#4ade80",
  brightYellow: "#facc15",
  brightBlue: "#60a5fa",
  brightMagenta: "#c084fc",
  brightCyan: "#22d3ee",
  brightWhite: "#ffffff",
};

function resolveOklch(value: string): string {
  const el = document.createElement("div");
  el.style.color = value;
  document.body.appendChild(el);
  const rgb = getComputedStyle(el).color;
  document.body.removeChild(el);
  return rgb;
}

function getCSSVar(name: string): string {
  const raw = getComputedStyle(document.documentElement)
    .getPropertyValue(name)
    .trim();
  if (!raw) return "";
  return resolveOklch(raw);
}

function buildThemeFromCSS(): ITheme {
  return {
    background: getCSSVar("--background"),
    foreground: getCSSVar("--foreground"),
    cursor: getCSSVar("--foreground"),
    cursorAccent: getCSSVar("--background"),
    selectionBackground: getCSSVar("--accent"),
    selectionForeground: getCSSVar("--accent-foreground"),
    ...ANSI_COLORS,
  };
}

// TODO: re-enable as "system theme" option in settings
// function buildXtermTheme(t: ThemeColors): ITheme {
//   return {
//     background: t.background, foreground: t.foreground, cursor: t.cursor,
//     selectionBackground: t.selection_background, selectionForeground: t.selection_foreground,
//     black: t.color0, red: t.color1, green: t.color2, yellow: t.color3,
//     blue: t.color4, magenta: t.color5, cyan: t.color6, white: t.color7,
//     brightBlack: t.color8, brightRed: t.color9, brightGreen: t.color10, brightYellow: t.color11,
//     brightBlue: t.color12, brightMagenta: t.color13, brightCyan: t.color14, brightWhite: t.color15,
//   };
// }

function extractBytes(payload: unknown): Uint8Array | null {
  if (payload instanceof Uint8Array) return payload;
  if (payload instanceof ArrayBuffer) return new Uint8Array(payload);
  if (Array.isArray(payload)) return new Uint8Array(payload as number[]);
  if (typeof payload === "string") return new TextEncoder().encode(payload);
  return null;
}

export function TerminalPane({ sessionId, focused, visible }: Props) {
  // TODO: re-enable as "system theme" option in settings
  // const { theme, shellAppearance } = useThemeColors();

  // Refs for mutable state that persists across renders
  const shellRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const termRef = useRef<Terminal | null>(null);
  const fitAddonRef = useRef<FitAddon | null>(null);
  const attachedSessionRef = useRef<string | null>(null);
  const kittyLevelRef = useRef(0);
  const pendingPtyWrites = useRef<Uint8Array[]>([]);
  const ptyWriteFrameRef = useRef<number | null>(null);
  const statusRef = useRef<TerminalStatusPayload>({
    session_id: sessionId,
    state: "starting",
    message: "Starting shell...",
    exit_code: null,
  });
  const statusOverlayRef = useRef<HTMLDivElement>(null);
  const ptyDecoderRef = useRef(new TextDecoder("utf-8", { fatal: false }));
  const blockNewlineRef = useRef<((e: Event) => void) | null>(null);
  const dataDisposableRef = useRef<{ dispose: () => void } | null>(null);
  const resizeObserverRef = useRef<ResizeObserver | null>(null);
  const resizeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const windowResizeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Track latest sessionId for closures
  const sessionIdRef = useRef(sessionId);
  sessionIdRef.current = sessionId;
  // Track props for closures
  const visibleRef = useRef(visible);
  visibleRef.current = visible;

  // ── Kitty protocol scanning ──
  const scanKittyProtocol = useCallback((data: Uint8Array | string) => {
    const str =
      typeof data === "string"
        ? data
        : ptyDecoderRef.current.decode(data);

    if (str.includes("\x1b[?u")) {
      writeToPty(sessionIdRef.current, "\x1b[?0u").catch(console.error);
    }

    const pushes = (str.match(/\x1b\[>[0-9]+u/g) ?? []).length;
    const pops = (str.match(/\x1b\[<u/g) ?? []).length;
    kittyLevelRef.current = Math.max(
      0,
      kittyLevelRef.current + pushes - pops,
    );
  }, []);

  // ── PTY output batching ──
  const flushPtyWrites = useCallback(() => {
    ptyWriteFrameRef.current = null;
    const term = termRef.current;
    const pending = pendingPtyWrites.current;
    if (!term || pending.length === 0) return;

    if (pending.length === 1) {
      term.write(pending[0]);
    } else {
      let totalLen = 0;
      for (const chunk of pending) totalLen += chunk.length;
      const combined = new Uint8Array(totalLen);
      let offset = 0;
      for (const chunk of pending) {
        combined.set(chunk, offset);
        offset += chunk.length;
      }
      term.write(combined);
    }
    pendingPtyWrites.current = [];
  }, []);

  const writePtyChunk = useCallback(
    (payload: unknown) => {
      if (!termRef.current) return;
      const bytes = extractBytes(payload);
      if (!bytes) return;

      scanKittyProtocol(bytes);
      pendingPtyWrites.current.push(bytes);
      if (ptyWriteFrameRef.current === null) {
        ptyWriteFrameRef.current = requestAnimationFrame(flushPtyWrites);
      }
    },
    [scanKittyProtocol, flushPtyWrites],
  );

  // ── Resize sync ──
  const syncTerminalSize = useCallback(async () => {
    const term = termRef.current;
    const fitAddon = fitAddonRef.current;
    if (!term || !fitAddon || !visibleRef.current) return;

    fitAddon.fit();
    if (term.cols === 0 || term.rows === 0) return;

    try {
      await resizePty(sessionIdRef.current, term.cols, term.rows);
    } catch (err) {
      console.error("Failed to resize PTY:", err);
    }
  }, []);

  // ── Update status overlay ──
  const updateStatusOverlay = useCallback((status: TerminalStatusPayload) => {
    statusRef.current = status;
    const el = statusOverlayRef.current;
    if (!el) return;
    if (status.state === "ready") {
      el.style.display = "none";
    } else {
      el.style.display = "flex";
      el.className = `terminal-overlay ${status.state}`;
      const h2 = el.querySelector("h2");
      const p = el.querySelector("p");
      const code = el.querySelector(".status-meta");
      if (h2)
        h2.textContent =
          status.state === "failed"
            ? "Terminal unavailable"
            : "Terminal starting";
      if (p) p.textContent = status.message ?? "Waiting for shell status...";
      if (code)
        code.textContent =
          status.exit_code !== null ? `Exit code: ${status.exit_code}` : "";
    }
  }, []);

  // ── Terminal status event ──
  useTauriEvent(
    onTerminalStatus,
    useCallback(
      (payload: TerminalStatusPayload) => {
        if (payload.session_id !== sessionIdRef.current) return;
        updateStatusOverlay(payload);
      },
      [updateStatusOverlay],
    ),
    [],
  );

  // ── Main mount/teardown effect ──
  useEffect(() => {
    const sid = sessionId;
    const containerEl = containerRef.current;
    if (!containerEl) return;

    // ── Create terminal ──
    const term = new Terminal({
      fontFamily: "'JetBrains Mono Variable', monospace",
      theme: buildThemeFromCSS(),
      convertEol: true,
      cursorBlink: true,
      cursorWidth: 2,
      lineHeight: 1.15,
      letterSpacing: 0,
      fontSize: 13,
      cursorStyle: "bar",
      altClickMovesCursor: true,
    });

    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);
    term.open(containerEl);

    termRef.current = term;
    fitAddonRef.current = fitAddon;
    kittyLevelRef.current = 0;

    // ── Custom key handler ──
    term.attachCustomKeyEventHandler((ev) => {
      // Shift+Enter
      if (ev.shiftKey && ev.key === "Enter") {
        if (kittyLevelRef.current > 0) {
          if (ev.type === "keydown") {
            writeToPty(sid, "\x1b[13;2u").catch(console.error);
          }
          ev.preventDefault?.();
          return false;
        }
        return true;
      }
      // Ctrl+Backspace → Ctrl+W
      if (ev.ctrlKey && ev.key === "Backspace") {
        if (ev.type === "keydown") {
          writeToPty(sid, "\x17").catch(console.error);
        }
        ev.preventDefault?.();
        return false;
      }
      // Ctrl+Shift+C → copy
      if (ev.ctrlKey && ev.shiftKey && ev.key === "C") {
        if (ev.type === "keydown") {
          const selection = term.getSelection();
          if (selection) navigator.clipboard.writeText(selection).catch(console.error);
        }
        ev.preventDefault?.();
        return false;
      }
      // Ctrl+Shift+V → paste
      if (ev.ctrlKey && ev.shiftKey && ev.key === "V") {
        if (ev.type === "keydown") {
          navigator.clipboard
            .readText()
            .then((text) => { if (text) term.paste(text); })
            .catch(console.error);
        }
        ev.preventDefault?.();
        return false;
      }
      // App-level shortcuts — let them bubble to window handlers
      if (isAppShortcut(ev)) return false;
      return true;
    });

    // ── WKWebView newline bug workaround ──
    const blockNewline = (e: Event) => {
      if (kittyLevelRef.current <= 0) return;
      const ie = e as InputEvent;
      if (
        ie.inputType === "insertLineBreak" ||
        ie.inputType === "insertParagraph" ||
        (ie.inputType === "insertText" && ie.data === "\n")
      ) {
        e.stopPropagation();
        e.preventDefault();
      }
    };
    containerEl.addEventListener("input", blockNewline, true);
    blockNewlineRef.current = blockNewline;

    // ── User input handler ──
    let pendingInput = "";
    let inputQueued = false;
    const dataDisposable = term.onData((data) => {
      pendingInput += data;
      if (!inputQueued) {
        inputQueued = true;
        queueMicrotask(() => {
          const batch = pendingInput;
          pendingInput = "";
          inputQueued = false;
          writeToPty(sid, batch).catch((err) => {
            console.error(`Failed to write to PTY for ${sid}:`, err);
          });
        });
      }
    });
    dataDisposableRef.current = dataDisposable;

    // ── Attach PTY session ──
    let cancelled = false;
    (async () => {
      try {
        const status = await getTerminalStatus(sid);
        if (cancelled) return;
        updateStatusOverlay(status);
      } catch {
        if (cancelled) return;
        updateStatusOverlay({
          session_id: sid,
          state: "failed",
          message: "Failed to read terminal status",
          exit_code: null,
        });
      }

      const channel = new Channel<unknown>((payload) => {
        writePtyChunk(payload);
      });

      try {
        await attachPtyOutput(sid, channel);
        if (cancelled) return;
        attachedSessionRef.current = sid;
      } catch (err) {
        if (cancelled) return;
        updateStatusOverlay({
          session_id: sid,
          state: "failed",
          message: `Failed to attach terminal output: ${String(err)}`,
          exit_code: null,
        });
        return;
      }

      // Initial size sync
      fitAddon.fit();
      if (term.cols > 0 && term.rows > 0) {
        resizePty(sid, term.cols, term.rows).catch(console.error);
      }
    })();

    // ── ResizeObserver ──
    const shellEl = shellRef.current;
    if (shellEl) {
      const observer = new ResizeObserver(() => {
        if (!visibleRef.current) return;
        if (resizeTimerRef.current !== null) {
          clearTimeout(resizeTimerRef.current);
        }
        resizeTimerRef.current = setTimeout(() => {
          resizeTimerRef.current = null;
          syncTerminalSize();
        }, 150);
      });
      observer.observe(shellEl);
      resizeObserverRef.current = observer;
    }

    // ── Window resize handler ──
    const windowResize = () => {
      if (!visibleRef.current) return;
      if (windowResizeTimerRef.current) clearTimeout(windowResizeTimerRef.current);
      windowResizeTimerRef.current = setTimeout(() => {
        windowResizeTimerRef.current = null;
        syncTerminalSize();
      }, 100);
    };
    window.addEventListener("resize", windowResize);

    // ── Cleanup ──
    return () => {
      cancelled = true;

      if (attachedSessionRef.current) {
        detachPtyOutput(attachedSessionRef.current).catch(console.error);
        attachedSessionRef.current = null;
      }
      dataDisposable.dispose();
      dataDisposableRef.current = null;

      if (ptyWriteFrameRef.current !== null) {
        cancelAnimationFrame(ptyWriteFrameRef.current);
        ptyWriteFrameRef.current = null;
      }
      pendingPtyWrites.current = [];

      containerEl.removeEventListener("input", blockNewline, true);
      blockNewlineRef.current = null;

      if (resizeTimerRef.current !== null) {
        clearTimeout(resizeTimerRef.current);
        resizeTimerRef.current = null;
      }
      if (windowResizeTimerRef.current !== null) {
        clearTimeout(windowResizeTimerRef.current);
        windowResizeTimerRef.current = null;
      }

      resizeObserverRef.current?.disconnect();
      resizeObserverRef.current = null;

      window.removeEventListener("resize", windowResize);

      fitAddonRef.current = null;
      kittyLevelRef.current = 0;
      term.dispose();
      termRef.current = null;
    };
    // Intentionally depend only on sessionId — theme updates are handled separately
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  // TODO: re-enable as "system theme" option in settings
  // useEffect(() => {
  //   if (termRef.current) {
  //     termRef.current.options.theme = buildXtermTheme(theme);
  //   }
  // }, [theme]);
  //
  // useEffect(() => {
  //   if (termRef.current) {
  //     termRef.current.options.fontFamily = shellAppearance.font_family || "monospace";
  //     fitAddonRef.current?.fit();
  //   }
  // }, [shellAppearance]);

  // ── Re-read CSS variables when theme class/style changes ──
  useEffect(() => {
    const observer = new MutationObserver(() => {
      if (termRef.current) {
        termRef.current.options.theme = buildThemeFromCSS();
      }
    });
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "style"],
    });
    return () => observer.disconnect();
  }, []);

  // ── Focus management ──
  useEffect(() => {
    if (focused && termRef.current) {
      termRef.current.focus();
    }
  }, [focused]);

  return (
    <div ref={shellRef} className="relative flex flex-1 w-full h-full min-w-0 min-h-0 bg-background">
      <div
        ref={containerRef}
        className="block flex-1 w-full h-full min-w-0 min-h-0 overflow-hidden px-2 py-1.5 box-border [&_.xterm]:h-full [&_.xterm]:w-full [&_.xterm-viewport]:!bg-transparent"
      />
      <div
        ref={statusOverlayRef}
        className="terminal-overlay starting absolute inset-0 flex items-center justify-center p-4 bg-background/90"
        style={{ display: statusRef.current.state === "ready" ? "none" : "flex" }}
      >
        <div className="w-full max-w-[440px] p-4 border border-border rounded-sm bg-card">
          <h2 className="mb-2 text-sm font-semibold text-foreground">
            Terminal starting
          </h2>
          <p className="text-sm text-muted-foreground">
            {statusRef.current.message ?? "Waiting for shell status..."}
          </p>
          <span className="status-meta mt-3 inline-block text-xs text-primary" />
        </div>
      </div>
    </div>
  );
}

// src-old/components/panes/TerminalPane.svelte
<script lang="ts">
    import { onMount, tick } from 'svelte';
    import { Terminal } from '@xterm/xterm';
    import type { ITheme } from '@xterm/xterm';
    import { FitAddon } from '@xterm/addon-fit';
    import { WebglAddon } from '@xterm/addon-webgl';
    import { ClipboardAddon } from '@xterm/addon-clipboard';
    import { SearchAddon } from '@xterm/addon-search';
    import { Channel, invoke } from '@tauri-apps/api/core';
    import { listen } from '@tauri-apps/api/event';
    import { theme, fallbackTheme, shellAppearance, type ShellAppearance } from '../../stores/theme';
    import '@xterm/xterm/css/xterm.css';

    type DisposeHandle = { dispose: () => void };

    let { sessionId, focused = false, visible = true, title = '' }: { sessionId: string; focused: boolean; visible: boolean; title: string } = $props();

    interface TerminalStatusPayload {
        session_id: string;
        state: 'starting' | 'ready' | 'exited' | 'failed';
        message: string | null;
        exit_code: number | null;
    }

    let shellContainer: HTMLDivElement;
    let terminalContainer: HTMLDivElement;
    let term: Terminal | null = null;
    let fitAddon: FitAddon | null = null;
    let resizeObserver: ResizeObserver | null = null;
    let resizeDebounceTimer: ReturnType<typeof setTimeout> | null = null;
    let windowResizeTimer: ReturnType<typeof setTimeout> | null = null;
    let webglAddon: WebglAddon | null = null;
    let pendingPtyWrites: Uint8Array[] = [];
    let ptyWriteFrameId: number | null = null;
    let dataDisposable: DisposeHandle | null = null;
    let resizeHandler: (() => void) | null = null;
    let themeUnsubscribe: (() => void) | null = null;
    let shellAppearanceUnsubscribe: (() => void) | null = null;
    let statusUnlisten: (() => void) | null = null;
    let attachedSessionId: string | null = null;
    let blockNewlineInput: ((e: Event) => void) | null = null;
    // Tracks whether the running application has pushed the kitty keyboard protocol
    // (e.g. OpenCode/crossterm sends ESC [ > 1 u to enable enhanced key reporting).
    // When active, Shift+Enter is sent as the CSI u sequence instead of \r.
    let kittyProtocolLevel = 0;
    const ptyDecoder = new TextDecoder('utf-8', { fatal: false });
    let terminalStatus = $state<TerminalStatusPayload>({
        session_id: '',
        state: 'starting',
        message: 'Starting shell...',
        exit_code: null
    });

    // Dimension tracking for smart placeholder.
    // Start large so normal-sized panes mount immediately without flash.
    let paneWidth = $state(9999);
    let paneHeight = $state(9999);
    let showPlaceholder = $state(false);

    // Hysteresis: unmount at <200x100, remount at >220x110 to prevent flickering
    // when dragging a resize handle near the boundary.
    $effect(() => {
        if (paneWidth < 200 || paneHeight < 100) {
            showPlaceholder = true;
        } else if (paneWidth > 220 && paneHeight > 110) {
            showPlaceholder = false;
        }
    });

    $effect(() => {
        terminalStatus.session_id = sessionId;
    });

    function terminalTheme(): ITheme {
        const css = getComputedStyle(document.documentElement);
        return {
            background: css.getPropertyValue('--ui-layer-0').trim() || '#0d0f11',
            foreground: css.getPropertyValue('--theme-foreground').trim() || fallbackTheme.foreground,
            cursor: css.getPropertyValue('--theme-cursor').trim() || fallbackTheme.cursor,
            selectionBackground:
                css.getPropertyValue('--theme-selection-background').trim() || fallbackTheme.selection_background,
            selectionForeground:
                css.getPropertyValue('--theme-selection-foreground').trim() || fallbackTheme.selection_foreground,
            black: css.getPropertyValue('--theme-color0').trim() || fallbackTheme.color0,
            red: css.getPropertyValue('--theme-color1').trim() || fallbackTheme.color1,
            green: css.getPropertyValue('--theme-color2').trim() || fallbackTheme.color2,
            yellow: css.getPropertyValue('--theme-color3').trim() || fallbackTheme.color3,
            blue: css.getPropertyValue('--theme-color4').trim() || fallbackTheme.color4,
            magenta: css.getPropertyValue('--theme-color5').trim() || fallbackTheme.color5,
            cyan: css.getPropertyValue('--theme-color6').trim() || fallbackTheme.color6,
            white: css.getPropertyValue('--theme-color7').trim() || fallbackTheme.color7,
            brightBlack: css.getPropertyValue('--theme-color8').trim() || fallbackTheme.color8,
            brightRed: css.getPropertyValue('--theme-color9').trim() || fallbackTheme.color9,
            brightGreen: css.getPropertyValue('--theme-color10').trim() || fallbackTheme.color10,
            brightYellow: css.getPropertyValue('--theme-color11').trim() || fallbackTheme.color11,
            brightBlue: css.getPropertyValue('--theme-color12').trim() || fallbackTheme.color12,
            brightMagenta: css.getPropertyValue('--theme-color13').trim() || fallbackTheme.color13,
            brightCyan: css.getPropertyValue('--theme-color14').trim() || fallbackTheme.color14,
            brightWhite: css.getPropertyValue('--theme-color15').trim() || fallbackTheme.color15
        };
    }

    function applyTerminalTheme() {
        if (!term) {
            return;
        }

        term.options.theme = terminalTheme();
    }

    // Scan PTY output for kitty keyboard protocol sequences.
    //
    // Detection works in two steps:
    //
    // Step 1 — capability query (crossterm sends \x1b[?u\x1b[c together):
    //   crossterm races the kitty-flags response against the DA1 response.
    //   If the kitty-flags response (\x1b[?<n>u) arrives FIRST, it knows the
    //   terminal supports keyboard enhancement.  xterm.js never responds to
    //   \x1b[?u, so crossterm only ever sees the DA1 response and concludes
    //   "not supported."  We fix this by detecting \x1b[?u in PTY output and
    //   immediately writing \x1b[?0u back to the PTY (meaning "supported, but
    //   no flags currently active").  This invoke is dispatched *before*
    //   term.write() runs, so it beats xterm.js's own DA1 response through the
    //   onData → queueMicrotask → invoke chain.
    //
    // Step 2 — push/pop tracking:
    //   Once crossterm knows the terminal supports enhancement it pushes its
    //   desired flags (\x1b[>Nu).  We count push/pop depth so that
    //   customKeyEventHandler knows when to send CSI u sequences vs plain \r.
    function scanKittyProtocol(data: Uint8Array | string): void {
        const str = typeof data === 'string' ? data : ptyDecoder.decode(data);

        // Step 1: respond to capability query before DA1 response can arrive.
        // \x1b[?u with no digits = the kitty keyboard capability query.
        // (A DEC private sequence \x1b[?<digits>h/l would have digits before the
        // final byte, so \x1b[?u cannot be confused with those.)
        if (str.includes('\x1b[?u')) {
            invoke('write_to_pty', { data: '\x1b[?0u', sessionId }).catch(console.error);
        }

        // Step 2: track push/pop depth.
        // Push: ESC [ > <flags> u  (e.g. \x1b[>1u sent by crossterm after detecting support)
        // Pop:  ESC [ < u
        const pushes = (str.match(/\x1b\[>[0-9]+u/g) ?? []).length;
        const pops   = (str.match(/\x1b\[<u/g)       ?? []).length;
        kittyProtocolLevel = Math.max(0, kittyProtocolLevel + pushes - pops);
    }

    function extractBytes(payload: unknown): Uint8Array | null {
        if (payload instanceof Uint8Array) return payload;
        if (payload instanceof ArrayBuffer) return new Uint8Array(payload);
        if (Array.isArray(payload)) return new Uint8Array(payload as number[]);
        if (typeof payload === 'string') return new TextEncoder().encode(payload);
        return null;
    }

    function flushPtyWrites() {
        ptyWriteFrameId = null;
        if (!term || pendingPtyWrites.length === 0) return;

        if (pendingPtyWrites.length === 1) {
            term.write(pendingPtyWrites[0]);
        } else {
            let totalLen = 0;
            for (const chunk of pendingPtyWrites) totalLen += chunk.length;
            const combined = new Uint8Array(totalLen);
            let offset = 0;
            for (const chunk of pendingPtyWrites) {
                combined.set(chunk, offset);
                offset += chunk.length;
            }
            term.write(combined);
        }
        pendingPtyWrites = [];
    }

    function writePtyChunk(payload: unknown) {
        if (!term) return;

        const bytes = extractBytes(payload);
        if (!bytes) return;

        // Scan protocol immediately — must not be deferred
        scanKittyProtocol(bytes);

        pendingPtyWrites.push(bytes);
        if (ptyWriteFrameId === null) {
            ptyWriteFrameId = requestAnimationFrame(flushPtyWrites);
        }
    }

    async function syncTerminalSize() {
        if (!term || !fitAddon || !visible) {
            return;
        }

        fitAddon.fit();

        if (term.cols === 0 || term.rows === 0) {
            return;
        }

        try {
            await invoke('resize_pty', { cols: term.cols, rows: term.rows, sessionId: sessionId });
        } catch (error) {
            console.error(`Failed to resize PTY for ${sessionId}:`, error);
        }
    }

    async function attachSession() {
        if (!term) {
            return;
        }

        if (attachedSessionId === sessionId) {
            await syncTerminalSize();
            return;
        }

        // Remember whether we're re-attaching to the *same* session that was
        // previously wired up (e.g. after a pane resize). In that case xterm
        // already holds the correct visible content, so we can skip clearing
        // the buffer and replaying the full pending_output history.
        // If we're switching to a *different* session (attachedSessionId !== null
        // but !== sessionId) we must clear so old content doesn't bleed
        // through — the early-return above already handles the identical-session
        // fast path, so reaching this point always means a session switch.
        const isReattachingSameSession = false;

        // New session: clear any previously tracked keyboard protocol state.
        kittyProtocolLevel = 0;

        if (attachedSessionId) {
            try {
                await invoke('detach_pty_output', { sessionId: attachedSessionId });
            } catch (error) {
                console.error(`Failed to detach terminal output for ${attachedSessionId}:`, error);
            }
        }

        if (!isReattachingSameSession) {
            term.clear();
        }
        attachedSessionId = sessionId;

        try {
            terminalStatus = await invoke<TerminalStatusPayload>('get_terminal_status', { sessionId: sessionId });
        } catch (error) {
            terminalStatus = {
                session_id: sessionId,
                state: 'failed',
                message: `Failed to read terminal status: ${String(error)}`,
                exit_code: null
            };
        }

        const ptyOutChannel = new Channel<unknown>((payload) => {
            writePtyChunk(payload);
        });

        try {
            await invoke('attach_pty_output', {
                channel: ptyOutChannel,
                sessionId: sessionId,
                skipPending: isReattachingSameSession,
            });
        } catch (error) {
            terminalStatus = {
                session_id: sessionId,
                state: 'failed',
                message: `Failed to attach terminal output: ${String(error)}`,
                exit_code: null
            };
        }

        await syncTerminalSize();
    }

    // Create xterm.js Terminal, load addons, open in container, attach PTY session.
    // Called on initial mount and when transitioning out of placeholder state.
    async function mountTerminal() {
        if (term || !terminalContainer) return;

        term = new Terminal({
            fontFamily: getComputedStyle(document.documentElement).getPropertyValue('--shell-font-family').trim() || 'monospace',
            theme: terminalTheme(),
            allowProposedApi: false,
            convertEol: true,
            cursorBlink: true,
            cursorWidth: 2,
            lineHeight: 1.15,
            letterSpacing: 0,
            fontSize: 13,
            cursorStyle: 'bar',
            altClickMovesCursor: true
        });

        // Add custom key handler for special key combos.
        //
        // IMPORTANT: xterm.js calls customKeyEventHandler for keydown, keypress,
        // AND keyup events.  WebKit fires keypress for Enter, so without the
        // `ev.type !== 'keydown'` guard below, every Shift+Enter would invoke
        // this handler twice and send two sequences to the PTY.  We guard all
        // data-sending branches to only act on keydown; for keypress/keyup we
        // still return false to suppress xterm's own handling of the same combo.
        term.attachCustomKeyEventHandler((ev) => {
            // Shift+Enter
            // - Kitty protocol active (e.g. OpenCode): send CSI 13;2u so the app sees
            //   "Shift+Enter" and inserts a newline without submitting.
            // - Kitty protocol not active (regular shell): return true so xterm handles
            //   it normally, sending \r — identical to plain Enter, which is the correct
            //   behaviour in a standard terminal.
            if (ev.shiftKey && ev.key === 'Enter') {
                if (kittyProtocolLevel > 0) {
                    if (ev.type === 'keydown') {
                        invoke('write_to_pty', { data: '\x1b[13;2u', sessionId }).catch(console.error);
                    }
                    ev.preventDefault?.();
                    return false;
                }
                return true;
            }
            // Ctrl+Backspace -> send Ctrl+W (backward-kill-word)
            if (ev.ctrlKey && ev.key === 'Backspace') {
                if (ev.type === 'keydown') {
                    invoke('write_to_pty', { data: '\x17', sessionId }).catch(console.error);
                }
                ev.preventDefault?.();
                return false;
            }
            // Ctrl+Shift+C -> copy (when text is selected)
            if (ev.ctrlKey && ev.shiftKey && ev.key === 'C') {
                if (ev.type === 'keydown') {
                    const selection = term?.getSelection();
                    if (selection) {
                        navigator.clipboard.writeText(selection).catch(console.error);
                    }
                }
                ev.preventDefault?.();
                return false;
            }
            // Ctrl+Shift+V -> paste
            if (ev.ctrlKey && ev.shiftKey && ev.key === 'V') {
                if (ev.type === 'keydown') {
                    navigator.clipboard.readText().then((text) => {
                        if (text && term) {
                            term.paste(text);
                        }
                    }).catch(console.error);
                }
                ev.preventDefault?.();
                return false;
            }
            // Tab management shortcuts — let these bubble to the window handler
            // instead of being consumed by xterm. Return false without
            // preventDefault so App.svelte's handleWindowKeydown picks them up.
            if (ev.ctrlKey && !ev.altKey) {
                const key = ev.key.toLowerCase();
                // Ctrl+T (new terminal tab), Ctrl+W (close tab)
                if (!ev.shiftKey && (key === 't' || key === 'w')) return false;
                // Ctrl+1 through Ctrl+9 (switch tab by index)
                if (!ev.shiftKey && ev.key >= '1' && ev.key <= '9') return false;
                // Ctrl+Shift+B (new browser tab), Ctrl+Shift+D (new diff tab)
                if (ev.shiftKey && (key === 'b' || key === 'd')) return false;
                // Ctrl+] and Ctrl+[ (workspace cycling)
                if (ev.key === ']' || ev.key === '[') return false;
            }
            return true;
        });

        fitAddon = new FitAddon();
        term.loadAddon(fitAddon);

        const clipboardAddon = new ClipboardAddon();
        term.loadAddon(clipboardAddon);

        const searchAddon = new SearchAddon();
        term.loadAddon(searchAddon);

        term.open(terminalContainer);

        // WKWebView (Tauri) does not reliably suppress `input` events on the
        // xterm helper textarea even after `preventDefault()` on `keydown`.
        // When kitty protocol is active and we intercept Shift+Enter in
        // `customKeyEventHandler`, the WKWebView still fires an `input` event
        // with `inputType: "insertText"` and `data: "\n"` (or
        // `"insertLineBreak"` with `data: null`).  xterm's `_inputEvent`
        // handler would call `onData("\n")` for the `insertText` variant,
        // doubling the newline we already sent as `\x1b[13;2u`.
        //
        // Fix: attach a capture-phase `input` listener on the container so it
        // fires before xterm's textarea listener.  When kitty protocol is
        // active we cancel any `input` event that would insert a newline.
        blockNewlineInput = (e: Event) => {
            if (kittyProtocolLevel <= 0) return;
            const ie = e as InputEvent;
            if (
                ie.inputType === 'insertLineBreak' ||
                ie.inputType === 'insertParagraph' ||
                (ie.inputType === 'insertText' && ie.data === '\n')
            ) {
                // Stop the event from reaching the xterm textarea listener so
                // xterm's _inputEvent handler never calls onData.  Use
                // stopPropagation (not stopImmediatePropagation) because xterm's
                // listener is on the child <textarea>, not on this container.
                e.stopPropagation();
                e.preventDefault();
            }
        };
        terminalContainer.addEventListener('input', blockNewlineInput, true);

        let pendingInput = '';
        let inputQueued = false;

        dataDisposable = term.onData((data) => {
            pendingInput += data;
            if (!inputQueued) {
                inputQueued = true;
                queueMicrotask(() => {
                    const batch = pendingInput;
                    pendingInput = '';
                    inputQueued = false;
                    invoke('write_to_pty', { data: batch, sessionId }).catch((error) => {
                        console.error(`Failed to write to PTY for ${sessionId}:`, error);
                        terminalStatus = {
                            session_id: sessionId,
                            state: 'failed',
                            message: `Failed to write to shell: ${String(error)}`,
                            exit_code: null
                        };
                    });
                });
            }
        });

        await attachSession();
    }

    // Dispose xterm.js Terminal and terminal-specific resources.
    // PTY session keeps running — only rendering is affected.
    function disposeTerminal() {
        if (attachedSessionId) {
            void invoke('detach_pty_output', { sessionId: attachedSessionId }).catch((error) => {
                console.error(`Failed to detach terminal output for ${attachedSessionId}:`, error);
            });
            attachedSessionId = null;
        }
        if (dataDisposable) {
            dataDisposable.dispose();
            dataDisposable = null;
        }
        if (ptyWriteFrameId !== null) {
            cancelAnimationFrame(ptyWriteFrameId);
            ptyWriteFrameId = null;
        }
        pendingPtyWrites = [];
        webglAddon?.dispose();
        webglAddon = null;
        if (blockNewlineInput && terminalContainer) {
            terminalContainer.removeEventListener('input', blockNewlineInput, true);
        }
        blockNewlineInput = null;
        fitAddon = null;
        term?.dispose();
        term = null;
        kittyProtocolLevel = 0;
    }

    // Mount/unmount terminal based on placeholder state.
    // When pane is too small, dispose xterm.js to save rendering resources.
    // When pane grows back, recreate terminal and reattach (PTY replays buffered output).
    $effect(() => {
        if (showPlaceholder) {
            if (term) disposeTerminal();
        } else if (!term) {
            // Use tick() to ensure the {:else} block has rendered and bind:this is set
            tick().then(() => {
                if (terminalContainer && !term) {
                    void mountTerminal();
                }
            });
        }
    });

    // Always-alive setup: subscriptions, listeners, and ResizeObserver that persist
    // across placeholder transitions. Terminal-specific setup is in mountTerminal().
    onMount(async () => {
        resizeHandler = () => {
            if (!visible) return;
            if (windowResizeTimer) clearTimeout(windowResizeTimer);
            windowResizeTimer = setTimeout(() => {
                windowResizeTimer = null;
                void syncTerminalSize();
            }, 100);
        };
        window.addEventListener('resize', resizeHandler);

        // Observe the always-present shell container (not terminal-wrapper which is
        // conditionally rendered) to track pane dimensions and sync terminal size.
        resizeObserver = new ResizeObserver((entries) => {
            for (const entry of entries) {
                paneWidth = entry.contentRect.width;
                paneHeight = entry.contentRect.height;
            }
            if (!visible || showPlaceholder) return;
            if (resizeDebounceTimer !== null) {
                clearTimeout(resizeDebounceTimer);
            }
            resizeDebounceTimer = setTimeout(() => {
                resizeDebounceTimer = null;
                void syncTerminalSize();
            }, 150);
        });
        resizeObserver.observe(shellContainer);

        themeUnsubscribe = theme.subscribe(() => {
            if (!visible) return;
            applyTerminalTheme();
        });

        shellAppearanceUnsubscribe = shellAppearance.subscribe((appearance: ShellAppearance | null) => {
            if (!term || !visible) {
                return;
            }

            term.options.fontFamily = appearance?.font_family?.trim() || 'monospace';
            fitAddon?.fit();
        });

        statusUnlisten = await listen<TerminalStatusPayload>('terminal-status', (event) => {
            if (event.payload.session_id !== sessionId) {
                return;
            }
            terminalStatus = event.payload;
        });

        // Initial terminal mount (placeholder starts false for normal-sized panes)
        if (!showPlaceholder && terminalContainer && !term) {
            await mountTerminal();
        }
    });

    $effect(() => {
        const sid = sessionId;
        if (!term || !sid || sid === attachedSessionId) {
            return;
        }

        void attachSession();
    });

    $effect(() => {
        if (!term) return;
        if (focused && visible) {
            if (!webglAddon) {
                try {
                    webglAddon = new WebglAddon();
                    webglAddon.onContextLoss(() => {
                        webglAddon?.dispose();
                        webglAddon = null;
                    });
                    term.loadAddon(webglAddon);
                } catch {
                    webglAddon = null;
                }
            }
        } else {
            if (webglAddon) {
                webglAddon.dispose();
                webglAddon = null;
            }
        }
    });

    onMount(() => {
        return () => {
            if (term) disposeTerminal();
            if (resizeHandler) {
                window.removeEventListener('resize', resizeHandler);
            }
            if (statusUnlisten) {
                statusUnlisten();
            }
            if (themeUnsubscribe) {
                themeUnsubscribe();
            }
            if (shellAppearanceUnsubscribe) {
                shellAppearanceUnsubscribe();
            }
            if (resizeDebounceTimer !== null) {
                clearTimeout(resizeDebounceTimer);
                resizeDebounceTimer = null;
            }
            if (windowResizeTimer !== null) {
                clearTimeout(windowResizeTimer);
                windowResizeTimer = null;
            }
            resizeObserver?.disconnect();
        };
    });
</script>

<div class="terminal-shell" bind:this={shellContainer}>
    {#if showPlaceholder}
        <div class="terminal-placeholder">
            <span class="placeholder-title">{title || 'shell'}</span>
        </div>
    {:else}
        <div class="terminal-wrapper" bind:this={terminalContainer}></div>
    {/if}

    {#if terminalStatus.state !== 'ready'}
        <div class={`terminal-overlay ${terminalStatus.state}`}>
            <div class="overlay-card">
                <h2>{terminalStatus.state === 'failed' ? 'Terminal unavailable' : 'Terminal starting'}</h2>
                <p>{terminalStatus.message ?? 'Waiting for shell status...'}</p>
                {#if terminalStatus.exit_code !== null}
                    <span class="status-meta">Exit code: {terminalStatus.exit_code}</span>
                {/if}
            </div>
        </div>
    {/if}
</div>

<style>
    .terminal-shell {
        position: relative;
        display: flex;
        flex: 1;
        width: 100%;
        height: 100%;
        min-width: 0;
        min-height: 0;
        background: var(--ui-layer-0, #0d0f11);
    }

    .terminal-wrapper {
        display: block;
        flex: 1;
        width: 100%;
        height: 100%;
        min-width: 0;
        min-height: 0;
        overflow: hidden;
        padding: 6px 8px 8px;
        box-sizing: border-box;
    }

    .terminal-placeholder {
        display: flex;
        align-items: center;
        justify-content: center;
        flex: 1;
        width: 100%;
        height: 100%;
        min-width: 0;
        min-height: 0;
        background: var(--ui-layer-0, #0d0f11);
        color: var(--text-muted, #555);
        font-size: 11px;
        font-family: var(--shell-font-family, monospace);
        user-select: none;
        opacity: 0.7;
    }

    .placeholder-title {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        max-width: 90%;
    }

    .terminal-overlay {
        position: absolute;
        inset: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 18px;
        background: color-mix(in srgb, var(--theme-background, #1a1b26) 88%, black 12%);
    }

    .overlay-card {
        width: min(440px, 100%);
        padding: 16px;
        border: 1px solid color-mix(in srgb, var(--theme-foreground, #c0caf5) 12%, transparent);
        border-radius: var(--ui-radius-lg);
        background: color-mix(in srgb, var(--theme-background, #1a1b26) 90%, white 10%);
    }

    .overlay-card h2 {
        margin: 0 0 8px;
        font-size: 0.92rem;
        font-weight: 600;
        color: var(--theme-foreground, #c0caf5);
    }

    .overlay-card p {
        margin: 0;
        line-height: 1.45;
        color: color-mix(in srgb, var(--theme-foreground, #c0caf5) 78%, white 22%);
    }

    .status-meta {
        display: inline-block;
        margin-top: 12px;
        font-size: 0.74rem;
        color: var(--theme-accent, #7aa2f7);
    }

    .terminal-overlay.failed .overlay-card {
        border-color: color-mix(in srgb, #f7768e 45%, transparent);
    }

    :global(.terminal-wrapper .terminal) {
        height: 100%;
        width: 100%;
    }

    :global(.terminal-wrapper .xterm) {
        padding-top: 2px;
    }

    :global(.terminal-wrapper .xterm),
    :global(.terminal-wrapper .xterm-viewport),
    :global(.terminal-wrapper .xterm-screen),
    :global(.terminal-wrapper .xterm-helpers) {
        width: 100%;
        height: 100%;
    }

    :global(.terminal-wrapper .xterm-viewport) {
        background: transparent !important;
    }
</style>
