// src/components/changes/ChangesPanel.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import DiffContent from '../diff/DiffContent.svelte';
    import { getGitStatus, getGitDiff, getGitBranchInfo, stageFiles, unstageFiles, commitChanges, pushChanges } from '../../stores/git';
    import type { GitFileStatus, GitBranchInfo } from '../../stores/types';

    let { workspaceCwd, onClose }: { workspaceCwd: string; onClose: () => void } = $props();

    let files = $state<GitFileStatus[]>([]);
    let branchInfo = $state<GitBranchInfo>({ branch: null, ahead: 0, behind: 0 });
    let expandedFile = $state<{ path: string; staged: boolean } | null>(null);
    let expandedDiffText = $state('');
    let commitMessage = $state('');
    let isLoading = $state(false);
    let isNotGitRepo = $state(false);

    let refreshTimer: ReturnType<typeof setInterval> | null = null;

    const stagedFiles = $derived(files.filter(f => f.is_staged === true));
    const unstagedFiles = $derived(files.filter(f => f.is_unstaged !== false));

    async function refresh() {
        try {
            const [statusResult, branchResult] = await Promise.all([
                getGitStatus(workspaceCwd),
                getGitBranchInfo(workspaceCwd),
            ]);
            files = statusResult;
            branchInfo = branchResult;
            isNotGitRepo = false;

            if (expandedFile && !files.some(f => f.path === expandedFile!.path)) {
                expandedFile = null;
                expandedDiffText = '';
            }
        } catch {
            isNotGitRepo = true;
            files = [];
        }
    }

    async function loadDiff(path: string, staged: boolean) {
        try {
            expandedDiffText = await getGitDiff(workspaceCwd, path, staged);
        } catch {
            expandedDiffText = '';
        }
    }

    async function handleToggleFile(path: string, staged: boolean) {
        if (expandedFile?.path === path && expandedFile?.staged === staged) {
            expandedFile = null;
            expandedDiffText = '';
        } else {
            expandedFile = { path, staged };
            await loadDiff(path, staged);
        }
    }

    async function handleStage(filePaths: string[]) {
        await stageFiles(workspaceCwd, filePaths);
        await refresh();
        if (expandedFile) await loadDiff(expandedFile.path, expandedFile.staged);
    }

    async function handleUnstage(filePaths: string[]) {
        await unstageFiles(workspaceCwd, filePaths);
        await refresh();
        if (expandedFile) await loadDiff(expandedFile.path, expandedFile.staged);
    }

    async function handleCommit() {
        if (!commitMessage.trim()) return;
        isLoading = true;
        try {
            await commitChanges(workspaceCwd, commitMessage.trim());
            commitMessage = '';
            expandedFile = null;
            expandedDiffText = '';
            await refresh();
        } catch (e) {
            console.error('commit failed:', e);
        }
        isLoading = false;
    }

    async function handlePush() {
        isLoading = true;
        try {
            await pushChanges(workspaceCwd);
            await refresh();
        } catch (e) {
            console.error('push failed:', e);
        }
        isLoading = false;
    }

    function handleCommitKeydown(event: KeyboardEvent) {
        if (event.key === 'Enter' && !event.shiftKey) {
            event.preventDefault();
            void handleCommit();
        }
    }

    function statusLetter(status: string): string {
        switch (status) {
            case 'added': return 'A';
            case 'modified': return 'M';
            case 'deleted': return 'D';
            case 'renamed': return 'R';
            case 'untracked': return 'U';
            case 'copied': return 'C';
            default: return '?';
        }
    }

    function statusClass(status: string): string {
        switch (status) {
            case 'added': return 'status-added';
            case 'modified': return 'status-modified';
            case 'deleted': return 'status-deleted';
            case 'renamed': return 'status-renamed';
            default: return 'status-muted';
        }
    }

    function fileName(path: string): string {
        const parts = path.split('/');
        return parts[parts.length - 1];
    }

    function handleActionClick(event: MouseEvent, action: 'stage' | 'unstage', path: string) {
        event.stopPropagation();
        if (action === 'stage') void handleStage([path]);
        else void handleUnstage([path]);
    }

    onMount(() => {
        void refresh();
        refreshTimer = setInterval(() => void refresh(), 3000);
        return () => {
            if (refreshTimer) clearInterval(refreshTimer);
        };
    });
</script>

<div class="changes-panel">
    <!-- Header -->
    <div class="panel-header">
        <span class="panel-title">Changes</span>
        {#if files.length > 0}
            <span class="file-count-badge">{files.length}</span>
        {/if}
        <div class="header-spacer"></div>
        <button class="header-btn" onclick={() => void refresh()} title="Refresh" aria-label="Refresh">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path d="M21 2v6h-6M3 22v-6h6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M3 12a9 9 0 0115.36-6.36L21 8M21 12a9 9 0 01-15.36 6.36L3 16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </button>
        <button class="header-btn close-btn" onclick={onClose} title="Close panel" aria-label="Close changes panel">
            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                <path d="M1.5 1.5l7 7M8.5 1.5l-7 7" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
            </svg>
        </button>
    </div>

    {#if isNotGitRepo}
        <div class="panel-empty">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" stroke="currentColor" stroke-width="1.5"/>
            </svg>
            <span>Not a git repository</span>
        </div>
    {:else}
        <!-- Commit controls -->
        <div class="commit-controls">
            <input
                class="commit-input"
                type="text"
                placeholder="Commit message..."
                bind:value={commitMessage}
                onkeydown={handleCommitKeydown}
            />
            <div class="commit-actions">
                <button
                    class="commit-btn"
                    onclick={() => void handleCommit()}
                    disabled={!commitMessage.trim() || !stagedFiles.length || isLoading}
                >
                    Commit
                </button>
                {#if branchInfo.ahead > 0}
                    <button
                        class="push-btn"
                        onclick={() => void handlePush()}
                        disabled={isLoading}
                    >
                        Push ↑{branchInfo.ahead}
                    </button>
                {/if}
            </div>
        </div>

        <!-- File sections -->
        <div class="file-sections">
            <!-- Staged section -->
            {#if stagedFiles.length > 0}
                <div class="section">
                    <div class="section-header">
                        <span class="section-label">Staged</span>
                        <span class="section-count">{stagedFiles.length}</span>
                        <button class="section-action" onclick={() => void handleUnstage(stagedFiles.map(f => f.path))}>
                            Unstage All
                        </button>
                    </div>
                    {#each stagedFiles as file (file.path + ':staged')}
                        <!-- svelte-ignore a11y_no_static_element_interactions -->
                        <div
                            class="file-row"
                            class:expanded={expandedFile?.path === file.path && expandedFile?.staged === true}
                            onclick={() => void handleToggleFile(file.path, true)}
                            onkeydown={(e) => { if (e.key === 'Enter') void handleToggleFile(file.path, true); }}
                            role="option"
                            tabindex="0"
                            aria-selected={expandedFile?.path === file.path && expandedFile?.staged === true}
                            title={file.path}
                        >
                            <span class="status-badge {statusClass(file.status)}">{statusLetter(file.status)}</span>
                            <span class="file-name">{fileName(file.path)}</span>
                            <button
                                class="action-btn unstage-btn"
                                onclick={(e) => handleActionClick(e, 'unstage', file.path)}
                                title="Unstage"
                            >
                                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                                    <path d="M1.5 5h7" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
                                </svg>
                            </button>
                        </div>
                        {#if expandedFile?.path === file.path && expandedFile?.staged === true}
                            <div class="inline-diff">
                                <DiffContent diffText={expandedDiffText} filePath={file.path} />
                            </div>
                        {/if}
                    {/each}
                </div>
            {/if}

            <!-- Unstaged section -->
            <div class="section">
                <div class="section-header">
                    <span class="section-label">Changes</span>
                    <span class="section-count">{unstagedFiles.length}</span>
                    {#if unstagedFiles.length > 0}
                        <button class="section-action" onclick={() => void handleStage(unstagedFiles.map(f => f.path))}>
                            Stage All
                        </button>
                    {/if}
                </div>
                {#each unstagedFiles as file (file.path + ':unstaged')}
                    <!-- svelte-ignore a11y_no_static_element_interactions -->
                    <div
                        class="file-row"
                        class:expanded={expandedFile?.path === file.path && expandedFile?.staged === false}
                        onclick={() => void handleToggleFile(file.path, false)}
                        onkeydown={(e) => { if (e.key === 'Enter') void handleToggleFile(file.path, false); }}
                        role="option"
                        tabindex="0"
                        aria-selected={expandedFile?.path === file.path && expandedFile?.staged === false}
                        title={file.path}
                    >
                        <span class="status-badge {statusClass(file.status)}">{statusLetter(file.status)}</span>
                        <span class="file-name">{fileName(file.path)}</span>
                        <button
                            class="action-btn stage-btn"
                            onclick={(e) => handleActionClick(e, 'stage', file.path)}
                            title="Stage"
                        >
                            <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                                <path d="M5 1.5v7M1.5 5h7" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/>
                            </svg>
                        </button>
                    </div>
                    {#if expandedFile?.path === file.path && expandedFile?.staged === false}
                        <div class="inline-diff">
                            <DiffContent diffText={expandedDiffText} filePath={file.path} />
                        </div>
                    {/if}
                {/each}
            </div>

            {#if stagedFiles.length === 0 && unstagedFiles.length === 0}
                <div class="panel-empty">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                        <path d="M20 6L9 17l-5-5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span>Working tree clean</span>
                </div>
            {/if}
        </div>
    {/if}
</div>

<style>
    .changes-panel {
        display: flex;
        flex-direction: column;
        width: 100%;
        height: 100%;
        min-width: 0;
        min-height: 0;
        overflow: hidden;
        background: var(--ui-layer-1);
        border-left: 1px solid var(--ui-border-soft);
    }

    /* Header */
    .panel-header {
        display: flex;
        align-items: center;
        gap: 6px;
        height: 40px;
        min-height: 40px;
        padding: 0 12px;
        border-bottom: 1px solid var(--ui-border-soft);
        flex-shrink: 0;
    }

    .panel-title {
        font-size: 0.8rem;
        font-weight: 600;
        color: var(--ui-text-primary);
    }

    .file-count-badge {
        font-size: 0.68rem;
        font-weight: 600;
        color: var(--ui-text-muted);
        background: var(--ui-layer-2);
        padding: 1px 6px;
        border-radius: var(--ui-radius-md);
    }

    .header-spacer {
        flex: 1;
    }

    .header-btn {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 24px;
        height: 24px;
        padding: 0;
        border: none;
        border-radius: var(--ui-radius-sm);
        background: transparent;
        color: var(--ui-text-muted);
        cursor: pointer;
        flex-shrink: 0;
        transition: all var(--ui-motion-fast);
    }

    .header-btn:hover {
        background: var(--ui-layer-2);
        color: var(--ui-text-secondary);
    }

    .close-btn:hover {
        background: color-mix(in srgb, var(--ui-danger) 12%, transparent);
        color: var(--ui-danger);
    }

    /* Commit controls */
    .commit-controls {
        display: flex;
        flex-direction: column;
        gap: 6px;
        padding: 8px 12px;
        border-bottom: 1px solid var(--ui-border-soft);
        flex-shrink: 0;
    }

    .commit-input {
        width: 100%;
        height: 28px;
        padding: 0 8px;
        background: var(--ui-layer-2);
        border: 1px solid var(--ui-border-soft);
        border-radius: var(--ui-radius-sm);
        color: var(--ui-text-primary);
        font-family: var(--ui-font-mono);
        font-size: 0.75rem;
        outline: none;
        box-sizing: border-box;
        transition: border-color var(--ui-motion-fast);
    }

    .commit-input:focus {
        border-color: color-mix(in srgb, var(--ui-accent) 36%, transparent);
    }

    .commit-input::placeholder {
        color: var(--ui-text-muted);
    }

    .commit-actions {
        display: flex;
        gap: 6px;
    }

    .commit-btn {
        flex: 1;
        height: 28px;
        padding: 0 12px;
        background: var(--ui-accent);
        border: none;
        border-radius: var(--ui-radius-sm);
        color: var(--ui-layer-0);
        font-size: 0.75rem;
        font-weight: 600;
        cursor: pointer;
        transition: opacity var(--ui-motion-fast);
    }

    .commit-btn:disabled {
        opacity: 0.4;
        cursor: default;
    }

    .commit-btn:not(:disabled):hover {
        opacity: 0.9;
    }

    .push-btn {
        height: 28px;
        padding: 0 10px;
        background: var(--ui-layer-2);
        border: 1px solid var(--ui-border-soft);
        border-radius: var(--ui-radius-sm);
        color: var(--ui-text-secondary);
        font-family: var(--ui-font-mono);
        font-size: 0.72rem;
        cursor: pointer;
        flex-shrink: 0;
        transition: all var(--ui-motion-fast);
    }

    .push-btn:hover {
        background: var(--ui-layer-3);
        color: var(--ui-text-primary);
    }

    .push-btn:disabled {
        opacity: 0.4;
        cursor: default;
    }

    /* File sections */
    .file-sections {
        flex: 1;
        overflow-y: auto;
        overflow-x: hidden;
        min-height: 0;
    }

    .section {
        margin-bottom: 4px;
    }

    .section-header {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 8px 12px 4px;
        flex-shrink: 0;
    }

    .section-label {
        font-size: 0.72rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.04em;
        color: var(--ui-text-muted);
    }

    .section-count {
        font-size: 0.68rem;
        font-weight: 600;
        color: var(--ui-text-muted);
        background: var(--ui-layer-2);
        padding: 1px 6px;
        border-radius: var(--ui-radius-md);
    }

    .section-action {
        margin-left: auto;
        padding: 2px 8px;
        border: 1px solid var(--ui-border-soft);
        border-radius: var(--ui-radius-sm);
        background: transparent;
        color: var(--ui-text-muted);
        font-size: 0.68rem;
        cursor: pointer;
        transition: all var(--ui-motion-fast);
    }

    .section-action:hover {
        background: var(--ui-layer-2);
        color: var(--ui-text-secondary);
    }

    /* File rows */
    .file-row {
        display: flex;
        align-items: center;
        gap: 8px;
        height: 28px;
        padding: 0 12px;
        cursor: pointer;
        transition: background var(--ui-motion-fast);
    }

    .file-row:hover {
        background: color-mix(in srgb, var(--ui-layer-2) 50%, transparent);
    }

    .file-row.expanded {
        background: var(--ui-layer-2);
    }

    .status-badge {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 16px;
        height: 16px;
        border-radius: var(--ui-radius-sm);
        font-family: var(--ui-font-mono);
        font-size: 0.65rem;
        font-weight: 700;
        flex-shrink: 0;
    }

    .status-added { color: var(--ui-success); background: color-mix(in srgb, var(--ui-success) 15%, transparent); }
    .status-modified { color: var(--ui-attention); background: color-mix(in srgb, var(--ui-attention) 15%, transparent); }
    .status-deleted { color: var(--ui-danger); background: color-mix(in srgb, var(--ui-danger) 15%, transparent); }
    .status-renamed { color: var(--ui-accent); background: color-mix(in srgb, var(--ui-accent) 15%, transparent); }
    .status-muted { color: var(--ui-text-muted); background: var(--ui-layer-2); }

    .file-name {
        flex: 1;
        min-width: 0;
        font-family: var(--ui-font-mono);
        font-size: 0.75rem;
        color: var(--ui-text-primary);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .action-btn {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 20px;
        padding: 0;
        border: none;
        border-radius: var(--ui-radius-sm);
        background: transparent;
        color: var(--ui-text-muted);
        cursor: pointer;
        flex-shrink: 0;
        opacity: 0;
        transition: all var(--ui-motion-fast);
    }

    .file-row:hover .action-btn {
        opacity: 1;
    }

    .stage-btn:hover {
        background: color-mix(in srgb, var(--ui-success) 15%, transparent);
        color: var(--ui-success);
    }

    .unstage-btn:hover {
        background: color-mix(in srgb, var(--ui-danger) 15%, transparent);
        color: var(--ui-danger);
    }

    /* Inline diff */
    .inline-diff {
        max-height: 300px;
        overflow-y: auto;
        border-top: 1px solid var(--ui-border-soft);
        border-bottom: 1px solid var(--ui-border-soft);
        background: var(--ui-layer-0);
    }

    /* Empty state */
    .panel-empty {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 8px;
        padding: 32px 16px;
        color: var(--ui-text-muted);
        font-size: 0.78rem;
        flex: 1;
    }
</style>

// src/components/workspace/changes-panel.tsx
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
} from "@/components/ui/tooltip";
import {
  Plus,
  Minus,
  GitCommit,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  Check,
  Trash2,
  Folder,
  ChevronRight,
  File,
} from "lucide-react";
import {
  getGitStatus,
  getGitDiff,
  getGitBranchInfo,
  gitStageFiles,
  gitUnstageFiles,
  gitCommitChanges,
  gitPushChanges,
  gitPullChanges,
  gitDiscardFile,
  gitLogEntries,
} from "@/tauri/commands";
import type {
  WorkspaceSnapshot,
  GitFileStatus,
  GitBranchInfo,
  GitLogEntry,
} from "@/tauri/types";

interface Props {
  workspace: WorkspaceSnapshot;
}

const STATUS_LABEL: Record<string, string> = {
  added: "A",
  modified: "M",
  deleted: "D",
  renamed: "R",
  untracked: "U",
  copied: "C",
};

const STATUS_COLOR: Record<string, string> = {
  added: "text-success",
  modified: "text-warning",
  deleted: "text-danger",
  renamed: "text-primary",
  untracked: "text-muted-foreground",
  copied: "text-muted-foreground",
};

// ── Helpers ──

function groupByDirectory(files: GitFileStatus[]): Array<{ dir: string; files: GitFileStatus[] }> {
  const map = new Map<string, GitFileStatus[]>();
  for (const file of files) {
    const lastSlash = file.path.lastIndexOf("/");
    const dir = lastSlash >= 0 ? file.path.substring(0, lastSlash) : "";
    const arr = map.get(dir) || [];
    arr.push(file);
    map.set(dir, arr);
  }
  // Sort: root ("") first, then alphabetical
  return Array.from(map.entries())
    .sort(([a], [b]) => {
      if (a === "") return -1;
      if (b === "") return 1;
      return a.localeCompare(b);
    })
    .map(([dir, files]) => ({ dir, files }));
}

function fileName(path: string): string {
  const idx = path.lastIndexOf("/");
  return idx >= 0 ? path.substring(idx + 1) : path;
}

// ── Diff View ──

function DiffView({ diff }: { diff: string }) {
  if (!diff) {
    return (
      <pre className="mx-1 mb-1 rounded-sm bg-muted/30 p-1.5 text-[10px] leading-normal font-mono text-muted-foreground">
        (empty diff)
      </pre>
    );
  }
  const lines = diff.split("\n");
  return (
    <div className="mx-1 mb-1 max-h-48 overflow-auto rounded-sm bg-muted/30 text-[10px] leading-normal font-mono">
      {lines.map((line, i) => {
        let cls = "px-1.5 whitespace-pre-wrap break-all";
        if (line.startsWith("+") && !line.startsWith("+++")) {
          cls += " text-success bg-success/10";
        } else if (line.startsWith("-") && !line.startsWith("---")) {
          cls += " text-danger bg-danger/10";
        } else if (line.startsWith("@@")) {
          cls += " text-muted-foreground/60 bg-muted/30 text-[9px]";
        } else {
          cls += " text-muted-foreground";
        }
        return (
          <div key={i} className={cls}>
            {line || " "}
          </div>
        );
      })}
    </div>
  );
}

// ── File Row ──

function FileRow({
  file,
  staged,
  cwd,
  expanded,
  onToggleExpand,
  onRefresh,
  indented,
}: {
  file: GitFileStatus;
  staged: boolean;
  cwd: string;
  expanded: boolean;
  onToggleExpand: () => void;
  onRefresh: () => void;
  indented?: boolean;
}) {
  const [diff, setDiff] = useState<string | null>(null);
  const [confirmDiscard, setConfirmDiscard] = useState(false);

  useEffect(() => {
    if (expanded) {
      getGitDiff(cwd, file.path, staged)
        .then(setDiff)
        .catch(() => setDiff("Failed to load diff"));
    } else {
      setDiff(null);
    }
  }, [expanded, cwd, file.path, staged]);

  const handleStageToggle = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      if (staged) {
        await gitUnstageFiles(cwd, [file.path]);
      } else {
        await gitStageFiles(cwd, [file.path]);
      }
      onRefresh();
    } catch (err) {
      console.error("Stage/unstage failed:", err);
    }
  };

  const handleDiscard = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirmDiscard) {
      setConfirmDiscard(true);
      setTimeout(() => setConfirmDiscard(false), 3000);
      return;
    }
    try {
      await gitDiscardFile(cwd, file.path);
      onRefresh();
    } catch (err) {
      console.error("Discard failed:", err);
    }
    setConfirmDiscard(false);
  };

  const name = fileName(file.path);

  return (
    <div>
      <Tooltip>
        <TooltipTrigger asChild>
          <button
            className={`group flex w-full items-center gap-1 rounded-sm py-0.5 text-left hover:bg-accent/50 transition-colors ${indented ? "pl-5 pr-1" : "px-1"}`}
            onClick={onToggleExpand}
          >
            <span
              className={`shrink-0 w-3.5 text-center text-[10px] font-bold leading-none ${STATUS_COLOR[file.status] ?? "text-muted-foreground"}`}
            >
              {STATUS_LABEL[file.status] ?? "?"}
            </span>
            <File className="h-3 w-3 shrink-0 text-muted-foreground/50" />
            <span className="flex-1 truncate text-xs text-foreground">{name}</span>
            {(file.additions > 0 || file.deletions > 0) && (
              <span className="flex items-center gap-0.5 shrink-0 text-[10px] tabular-nums">
                {file.additions > 0 && (
                  <span className="text-success">+{file.additions}</span>
                )}
                {file.deletions > 0 && (
                  <span className="text-danger">-{file.deletions}</span>
                )}
              </span>
            )}
            <div className="flex items-center shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
              {!staged && (
                <Button
                  variant="ghost"
                  size="icon-xs"
                  className={confirmDiscard ? "text-danger hover:text-danger" : "text-muted-foreground"}
                  onClick={handleDiscard}
                  title={confirmDiscard ? "Click again to discard" : "Discard changes"}
                >
                  <Trash2 className="h-3 w-3" />
                </Button>
              )}
              <Button
                variant="ghost"
                size="icon-xs"
                className="text-muted-foreground"
                onClick={handleStageToggle}
                title={staged ? "Unstage" : "Stage"}
              >
                {staged ? <Minus className="h-3 w-3" /> : <Plus className="h-3 w-3" />}
              </Button>
            </div>
          </button>
        </TooltipTrigger>
        <TooltipContent side="left" className="text-xs">
          {file.path}
        </TooltipContent>
      </Tooltip>
      {expanded && diff !== null && <DiffView diff={diff} />}
    </div>
  );
}

// ── Directory Group ──

function DirectoryGroup({
  dir,
  files,
  staged,
  cwd,
  expandedFile,
  expandedStaged,
  onToggleExpand,
  onRefresh,
}: {
  dir: string;
  files: GitFileStatus[];
  staged: boolean;
  cwd: string;
  expandedFile: string | null;
  expandedStaged: boolean;
  onToggleExpand: (path: string, staged: boolean) => void;
  onRefresh: () => void;
}) {
  const [collapsed, setCollapsed] = useState(false);

  // Root-level files (no directory) render without header
  if (dir === "") {
    return (
      <>
        {files.map((f) => (
          <FileRow
            key={f.path}
            file={f}
            staged={staged}
            cwd={cwd}
            expanded={expandedFile === f.path && expandedStaged === staged}
            onToggleExpand={() => onToggleExpand(f.path, staged)}
            onRefresh={onRefresh}
          />
        ))}
      </>
    );
  }

  return (
    <div>
      <button
        className="flex w-full items-center gap-1 px-1 py-0.5 text-left hover:bg-accent/30 transition-colors rounded-sm"
        onClick={() => setCollapsed(!collapsed)}
      >
        <ChevronRight
          className={`h-3 w-3 shrink-0 text-muted-foreground transition-transform ${!collapsed ? "rotate-90" : ""}`}
        />
        <Folder className="h-3 w-3 shrink-0 text-muted-foreground/50" />
        <span className="truncate text-[10px] text-muted-foreground">{dir}</span>
      </button>
      {!collapsed &&
        files.map((f) => (
          <FileRow
            key={f.path}
            file={f}
            staged={staged}
            cwd={cwd}
            expanded={expandedFile === f.path && expandedStaged === staged}
            onToggleExpand={() => onToggleExpand(f.path, staged)}
            onRefresh={onRefresh}
            indented
          />
        ))}
    </div>
  );
}

// ── File Section (Staged / Changes) ──

function FileSection({
  label,
  files,
  staged,
  cwd,
  expandedFile,
  expandedStaged,
  onToggleExpand,
  onRefresh,
  onBulkAction,
  bulkLabel,
}: {
  label: string;
  files: GitFileStatus[];
  staged: boolean;
  cwd: string;
  expandedFile: string | null;
  expandedStaged: boolean;
  onToggleExpand: (path: string, staged: boolean) => void;
  onRefresh: () => void;
  onBulkAction: () => void;
  bulkLabel: string;
}) {
  const groups = useMemo(() => groupByDirectory(files), [files]);

  return (
    <div className="py-1">
      <div className="flex items-center justify-between px-1.5 py-0.5">
        <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
          {label}
        </span>
        <div className="flex items-center gap-1.5">
          <span className="text-[10px] tabular-nums text-muted-foreground">{files.length}</span>
          <Button variant="ghost" size="xs" className="h-5 px-1.5 text-[10px]" onClick={onBulkAction}>
            {bulkLabel}
          </Button>
        </div>
      </div>
      {groups.map((group) => (
        <DirectoryGroup
          key={group.dir}
          dir={group.dir}
          files={group.files}
          staged={staged}
          cwd={cwd}
          expandedFile={expandedFile}
          expandedStaged={expandedStaged}
          onToggleExpand={onToggleExpand}
          onRefresh={onRefresh}
        />
      ))}
    </div>
  );
}

// ── Main Panel ──

export function ChangesPanel({ workspace }: Props) {
  const cwd = workspace.worktree_path ?? workspace.cwd;
  console.log("[ChangesPanel] cwd:", cwd, "worktree_path:", workspace.worktree_path, "workspace.cwd:", workspace.cwd);
  const [files, setFiles] = useState<GitFileStatus[]>([]);
  const [branchInfo, setBranchInfo] = useState<GitBranchInfo | null>(null);
  const [commits, setCommits] = useState<GitLogEntry[]>([]);
  const [expandedFile, setExpandedFile] = useState<string | null>(null);
  const [expandedStaged, setExpandedStaged] = useState(false);
  const [commitMsg, setCommitMsg] = useState("");
  const [busy, setBusy] = useState(false);
  const [commitsExpanded, setCommitsExpanded] = useState(false);
  const refreshRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const refresh = useCallback(() => {
    if (!cwd) return;
    Promise.all([
      getGitStatus(cwd).catch((e) => { console.error("[ChangesPanel] git status failed:", e); return [] as GitFileStatus[]; }),
      getGitBranchInfo(cwd).catch((e) => { console.error("[ChangesPanel] branch info failed:", e); return null; }),
      gitLogEntries(cwd, 10).catch((e) => { console.error("[ChangesPanel] git log failed:", e); return [] as GitLogEntry[]; }),
    ]).then(([status, info, log]) => {
      console.log("[ChangesPanel] status:", status.length, "files, branch:", info?.branch, "commits:", log.length);
      setFiles(status);
      if (info) setBranchInfo(info);
      setCommits(log);
    });
  }, [cwd]);

  useEffect(() => {
    refresh();
    refreshRef.current = setInterval(refresh, 3000);
    return () => {
      if (refreshRef.current) clearInterval(refreshRef.current);
    };
  }, [refresh]);

  const staged = useMemo(() => files.filter((f) => f.is_staged), [files]);
  const unstaged = useMemo(() => files.filter((f) => f.is_unstaged), [files]);

  const handleCommit = async () => {
    if (!commitMsg.trim() || staged.length === 0 || busy) return;
    setBusy(true);
    try {
      await gitCommitChanges(cwd, commitMsg.trim());
      setCommitMsg("");
      setExpandedFile(null);
      refresh();
    } catch (err) {
      console.error("Commit failed:", err);
    } finally {
      setBusy(false);
    }
  };

  const handlePush = async () => {
    if (busy) return;
    setBusy(true);
    try {
      await gitPushChanges(cwd);
      refresh();
    } catch (err) {
      console.error("Push failed:", err);
    } finally {
      setBusy(false);
    }
  };

  const handlePull = async () => {
    if (busy) return;
    setBusy(true);
    try {
      await gitPullChanges(cwd);
      refresh();
    } catch (err) {
      console.error("Pull failed:", err);
    } finally {
      setBusy(false);
    }
  };

  const handleStageAll = async () => {
    const paths = unstaged.map((f) => f.path);
    if (paths.length === 0) return;
    await gitStageFiles(cwd, paths).catch(console.error);
    refresh();
  };

  const handleUnstageAll = async () => {
    const paths = staged.map((f) => f.path);
    if (paths.length === 0) return;
    await gitUnstageFiles(cwd, paths).catch(console.error);
    refresh();
  };

  const handleToggleExpand = (path: string, isStaged: boolean) => {
    if (expandedFile === path && expandedStaged === isStaged) {
      setExpandedFile(null);
    } else {
      setExpandedFile(path);
      setExpandedStaged(isStaged);
    }
  };

  return (
    <TooltipProvider>
      <div className="flex h-full flex-col">
        {/* Commit bar — pinned at top */}
        <div className="p-1.5 space-y-1 border-b border-border">
          <Input
            placeholder="Commit message"
            value={commitMsg}
            onChange={(e) => setCommitMsg(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleCommit()}
            className="h-7 text-xs"
          />
          <div className="flex gap-1">
            <Button
              size="xs"
              className="flex-1 text-xs h-6"
              disabled={!commitMsg.trim() || staged.length === 0 || busy}
              onClick={handleCommit}
            >
              <GitCommit className="h-3 w-3 mr-1" />
              Commit
            </Button>
            {branchInfo && branchInfo.behind > 0 && (
              <Button
                size="xs"
                variant="secondary"
                className="text-xs h-6"
                disabled={busy}
                onClick={handlePull}
              >
                <ArrowDown className="h-3 w-3 mr-1" />
                Pull {branchInfo.behind}
              </Button>
            )}
            {branchInfo && branchInfo.ahead > 0 && (
              <Button
                size="xs"
                variant="secondary"
                className="text-xs h-6"
                disabled={busy}
                onClick={handlePush}
              >
                <ArrowUp className="h-3 w-3 mr-1" />
                Push {branchInfo.ahead}
              </Button>
            )}
            <Button
              size="xs"
              variant="ghost"
              className="h-6 w-6 p-0"
              onClick={refresh}
              title="Refresh"
            >
              <RefreshCw className="h-3 w-3" />
            </Button>
          </div>
        </div>

        {/* File list */}
        <ScrollArea className="flex-1">
          {files.length === 0 && (
            <div className="flex flex-col items-center justify-center min-h-[120px] text-muted-foreground">
              <Check className="h-5 w-5 mb-1.5 opacity-40" />
              <p className="text-xs">No changes</p>
            </div>
          )}

          <div className="px-1">
            {staged.length > 0 && (
              <FileSection
                label="Staged"
                files={staged}
                staged
                cwd={cwd}
                expandedFile={expandedFile}
                expandedStaged={expandedStaged}
                onToggleExpand={handleToggleExpand}
                onRefresh={refresh}
                onBulkAction={handleUnstageAll}
                bulkLabel="Unstage all"
              />
            )}

            {unstaged.length > 0 && (
              <FileSection
                label="Changes"
                files={unstaged}
                staged={false}
                cwd={cwd}
                expandedFile={expandedFile}
                expandedStaged={expandedStaged}
                onToggleExpand={handleToggleExpand}
                onRefresh={refresh}
                onBulkAction={handleStageAll}
                bulkLabel="Stage all"
              />
            )}

            {/* Recent Commits — collapsed by default */}
            {commits.length > 0 && (
              <div className="py-1">
                <button
                  className="flex w-full items-center justify-between px-1.5 py-0.5 hover:bg-accent/30 rounded-sm transition-colors"
                  onClick={() => setCommitsExpanded(!commitsExpanded)}
                >
                  <div className="flex items-center gap-1">
                    <ChevronRight
                      className={`h-3 w-3 shrink-0 text-muted-foreground transition-transform ${commitsExpanded ? "rotate-90" : ""}`}
                    />
                    <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                      Recent Commits
                    </span>
                  </div>
                  <span className="text-[10px] tabular-nums text-muted-foreground">
                    {commits.length}
                  </span>
                </button>
                {commitsExpanded &&
                  commits.map((commit) => (
                    <Tooltip key={commit.hash}>
                      <TooltipTrigger asChild>
                        <div className="flex items-start gap-1.5 rounded-sm px-1.5 py-1 hover:bg-accent/50 transition-colors">
                          <span className="shrink-0 text-[10px] font-mono text-primary">
                            {commit.short_hash}
                          </span>
                          <div className="flex-1 min-w-0">
                            <p className="truncate text-xs text-foreground">{commit.message}</p>
                            <p className="text-[10px] text-muted-foreground">
                              {commit.author} · {commit.time_ago}
                            </p>
                          </div>
                        </div>
                      </TooltipTrigger>
                      <TooltipContent side="left" className="text-xs max-w-64">
                        {commit.message}
                      </TooltipContent>
                    </Tooltip>
                  ))}
              </div>
            )}
          </div>
        </ScrollArea>
      </div>
    </TooltipProvider>
  );
}
